name: glassduck
favicon: null
layout_spectrum: 0.9820789
typography_spectrum: 0.13126
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: glassduck
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9d9d9d'
    - '#135c61'
    - '#489232'
    - '#a91c2b'
    - '#0993bb'
  brandStrength: 1
  lightness: 0.648334
  saturation: 1
  rhythmicContrast: 0.801748
purpose: []
