favicon: null
name: glassduck
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.1014522078912705
  lightness: 0.6483339678961784
  brandStrength: 0.7473118
  brandColors:
    - '#FFFFFF'
    - '#413B37'
    - '#BDBCB4'
    - '#397570'
    - '#B56E65'
  rhythmicContrast: 0.8017480140551925
typography_spectrum: 0
layout_spectrum: 0.9820789
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
