analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 1
title: glassduck
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.125
  brandStrength: 1
  rhythmicContrast: 1
  brandColors:
    - '#ffffff'
    - '#eb2a2e'
    - '#ed4b3c'
    - '#f7a890'
    - '#fbd1c1'
  lightness: 0.5
purpose: []
favicon: null
name: glassduck
typography_spectrum: 0.3978
