name: glassduck
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50601
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: glassduck
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5b80c6'
    - '#c8dbf9'
    - '#1d2623'
    - '#888d5d'
    - '#fffeea'
  brandStrength: 0.25
  lightness: 0.1875
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
